---
# # tasks file for roles/configure-jenkins
# ---
# - name: Ensure Jenkins is started
#   service:
#     name: jenkins
#     state: started
#     enabled: yes


# tasks file for roles/configure-jenkins
- name: Create Jenkins configuration directory
  file:
    path: /var/lib/jenkins/config
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Copy Jenkins configuration files
  copy:
    src: config.xml
    dest: /var/lib/jenkins/config/config.xml
    owner: jenkins
    group: jenkins
    mode: '0644'
